import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]

[env]
TERM = "xterm-256color"
[window]


#padding.x = 10
#padding.y = 10
dynamic_padding = true
decorations = "Buttonless"

opacity = 0.6
blur = true

dynamic_title = true

startup_mode = "Fullscreen"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 19

[selection]
save_to_clipboard = true

[cursor]
style.blinking = "On"
unfocused_hollow = true

[keyboard]
bindings = [
 { key = "V",              mods = "Command",                    action = "Paste"                 },
 { key = "C",              mods = "Command",                    action = "Copy"                  },
 { key = "H",              mods = "Command",                    action = "Hide"                  },
 { key = "M",              mods = "Command",                    action = "Minimize"              },
 { key = "Q",              mods = "Command",                    action = "Quit"                  },
 { key = "W",              mods = "Command",                    action = "Quit"                  },
 { key = "N",              mods = "Command",                    action = "SpawnNewInstance"      },
 { key = "F",              mods = "Command|Control",            action = "ToggleFullscreen"      },
 { key = "F",              mods = "Command", mode = "~Search",     action = "SearchForward"         },
 { key = "B",              mods = "Command", mode = "~Search",     action = "SearchBackward"        }
  ]
